### ISSUE TITLE
Trouble in compile the source

### ISSUE THREAD

**Issue by danroma87** [wg/scrypt#16]
Hi all,
I launched the mvn install everything look good except when dealing with surefire:

SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
[INFO] Scanning for projects...
[INFO]  
[INFO] ------------------------------------------------------------------------
[INFO] Building scrypt 1.4.0
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.5:resources (default-resources) @ scrypt ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ scrypt ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-resources-plugin:2.5:testResources (default-testResources) @ scrypt ---
[debug] execute contextualize
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 5 resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ scrypt ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- maven-surefire-plugin:2.10:test (default-test) @ scrypt ---
[INFO] Surefire report directory: /Users/daN/git/scrypt/target/surefire-reports

---
##  T E S T S

java.lang.NoClassDefFoundError: org/junit/runner/notification/RunListener
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2446)
    at java.lang.Class.getConstructor0(Class.java:2756)
    at java.lang.Class.getConstructor(Class.java:1693)
    at org.apache.maven.surefire.util.ReflectionUtils.getConstructor(ReflectionUtils.java:76)
    at org.apache.maven.surefire.util.ReflectionUtils.instantiateOneArg(ReflectionUtils.java:129)
    at org.apache.maven.surefire.booter.SurefireReflector.instantiateProvider(SurefireReflector.java:247)
    at org.apache.maven.surefire.booter.ProviderFactory.createProvider(ProviderFactory.java:81)
    at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:171)
    at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: java.lang.ClassNotFoundException: org.junit.runner.notification.RunListener
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at org.apache.maven.surefire.booter.IsolatedClassLoader.loadClass(IsolatedClassLoader.java:93)
    ... 11 more

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jar-plugin:2.3.2:jar (default-jar) @ scrypt ---
[INFO] Building jar: /Users/daN/git/scrypt/target/scrypt-1.4.0.jar
[INFO] META-INF/maven/com.lambdaworks/scrypt/pom.xml already added, skipping
[INFO] META-INF/maven/com.lambdaworks/scrypt/pom.properties already added, skipping
[INFO] 
[INFO] --- maven-surefire-plugin:2.10:test (integration-test) @ scrypt ---
[INFO] Surefire report directory: /Users/daN/git/scrypt/target/surefire-reports

---
##  T E S T S

java.lang.NoClassDefFoundError: org/junit/runner/notification/RunListener
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2446)
    at java.lang.Class.getConstructor0(Class.java:2756)
    at java.lang.Class.getConstructor(Class.java:1693)
    at org.apache.maven.surefire.util.ReflectionUtils.getConstructor(ReflectionUtils.java:76)
    at org.apache.maven.surefire.util.ReflectionUtils.instantiateOneArg(ReflectionUtils.java:129)
    at org.apache.maven.surefire.booter.SurefireReflector.instantiateProvider(SurefireReflector.java:247)
    at org.apache.maven.surefire.booter.ProviderFactory.createProvider(ProviderFactory.java:81)
    at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:171)
    at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)
Caused by: java.lang.ClassNotFoundException: org.junit.runner.notification.RunListener
    at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at org.apache.maven.surefire.booter.IsolatedClassLoader.loadClass(IsolatedClassLoader.java:93)
    ... 11 more

Results :

Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

[INFO] 
[INFO] --- maven-jarsigner-plugin:1.2:sign (sign) @ scrypt ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6.646s
[INFO] Finished at: Sat Feb 01 23:42:52 CET 2014
[INFO] Final Memory: 5M/81M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-jarsigner-plugin:1.2:sign (sign) on project scrypt: The parameters 'alias' for goal org.apache.maven.plugins:maven-jarsigner-plugin:1.2:sign are missing or invalid -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginParameterException

Please help!

**Comment by danroma87** [comment]
just a maven issue... continuing with the compiling..

**Comment by danroma87** [comment]
anyway I still don't understand how it works... i compiled correct the jar, the maven goals all goes ok... now?
